DROP TABLE users IF EXISTS CASCADE;

CREATE TABLE IF NOT EXISTS users (
    ID INTEGER IDENTITY(1, 1) NOT NULL,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);